import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>LivrariaCRUD</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Bem-Vindo(a) <a>Livraria CRUD</a>
        </h1>

        <div className={styles.grid}>
          <a href="/" className={styles.card}>
            <h2>Cadastrar Autor(a) &rarr;</h2>
            <p>Cadastre aqui seus autores.</p>
          </a>

          <a href="/" className={styles.card}>
            <h2>Cadastrar Livro &rarr;</h2>
            <p>Cadastre aqui seus livros.</p>
          </a>

          <a href="/" className={styles.card}>
            <h2>Vizualizar Autores &rarr;</h2>
            <p>Vizualize aqui todos os seus autores cadastrados.</p>
          </a>

          <a href="/" className={styles.card}>
            <h2>Vizualizar Livros &rarr;</h2>
            <p>
              Vizualize aqui todos os seus livros cadastrados.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a>
        <b>Lucas Godoy | Jorge Leandro</b> 
        </a>
      </footer>
    </div>
  )
}
